import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 24,
    },
    headerContainer: {
        alignItems: 'center',
        marginTop: 40,
        marginBottom: 40,
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#232B42',
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 14,
        color: '#121212',
        fontWeight: '400',
    },
    inputSection: {
        marginBottom: 20,
    },
    label: {
        fontSize: 14,
        color: '#121212',
        marginBottom: 8,
        fontWeight: '500',
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E5E5E5',
        borderRadius: 12,
        paddingHorizontal: 12,
        height: 52,
        backgroundColor: '#FAFAFA',
    },
    input: {
        flex: 1,
        fontSize: 16,
        color: '#121212',
        height: '100%',
        fontWeight: '500',
    },
    submitButton: {
        backgroundColor: '#232B42',
        borderRadius: 8,
        height: 52,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 20,
        marginBottom: 40,
    },
    submitButtonText: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: 'bold',
    },
    mainContainer: {
        flexGrow: 1,
        backgroundColor: '#FFFFFF',
    },
    imagePickerContainer: {
        alignItems: 'center',
        marginBottom: 30,
        marginTop: 10,
    },
    imagePicker: {
        width: 120,
        height: 120,
        borderRadius: 100,
        backgroundColor: '#F5F5F5',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#121212',
    },
    selectedImage: {
        width: '100%',
        height: '100%',
        borderRadius: 100,
    },
    cameraIcon: {
        width: 30,
        height: 30,
        tintColor: '#121212',
    },
    editIconContainer: {
        position: 'absolute',
        bottom: 5,
        right: 0,
        backgroundColor: '#232B42',
        width: 28,
        height: 28,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#FFFFFF',
    },
    editIconText: {
        color: '#FFFFFF',
        fontSize: 16,
        lineHeight: 18,
    },
    genderContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 5,
    },
    genderOption: {
        flex: 1,
        paddingVertical: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E5E5E5',
        borderRadius: 8,
        marginHorizontal: 4,
        backgroundColor: '#FAFAFA',
    },
    genderOptionSelected: {
        borderColor: '#232B42',
        backgroundColor: '#232B42',
    },
    genderText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#121212',
    },
    genderTextSelected: {
        color: '#FFFFFF',
    },
});
